### ISSUE TITLE
Unable to reset

### ISSUE THREAD

**Issue by AMDmi3** [maks/MGit#238] opened 2017-12-29 23:25 UTC
Regardless of what I do (nothing - clean repo; adding files; editing files; staging and not staging changes) the reset command does not work saying **Wrong Repository State: SAFE**

**Comment by maks** [comment] 2018-01-08 04:30
Thank you for filing this issue.
Would you have a publicly accessible repo that I could use to reproduce this bug?

**Comment by AMDmi3** [comment] 2018-01-08 09:42
It reproduces on any repo for me.

**Comment by superfury** [comment] 2018-01-23 09:05
I get this too when trying to reset the repository after pulling my application repository (https://bitbucket.org/superfury/unipcemu.git) when I've committed a change in my common emulator framework submodule. After committing the new link(required according to SmartGit) and pushing it to the UniPCemu repository, when pulling the repository to MGit on my Android device, MGit shows me that the subrepository is unchanged. The only way to get rid of that is committing, going back to my PC and manually reversing the commit, then pulling those changes back into Android MGit.

So there seems to be a problem with handling subrepositories(not updating links to when it's updated?). Also, when I have some local changes on my Android device for the main repository, I actually MUST commit it together with the incorrect subrepository link(bringing the submodule back into it's old state) in order to get the file(s) in the main repository to be committed at all. The discard option gives a **Wrong Repository State: SAFE** when used.

**Comment by superfury** [comment] 2018-01-27 04:44
So in other words: pulling a new subrepository commit doesn't update said link(file containing the commit of the repository to link to). The subrepository keeps it's old link(to the hash before pulling the changes, which might have been updated several times in the pulled commits), but said changes to the subrepository(and maybe even the data within it's repository as well) aren't applied in the files, causing the infixable bug(except recloning recursively after deleting the main repository)?

**Comment by maks** [comment] 2018-01-31 09:58
sorry I've not had much time to work on the MGit recently.
I can replicate this issue too - no idea though when or why its started happening.
Anyway I'm, sorry this is causing such an inconvenient problem. I have enough information to work on it, I'll advise here once I've had a chance to work on a fix.

**Comment by polyzen** [comment] 2018-02-25 22:56
Related to #195?

**Comment by KOLANICH** [comment] 2018-03-25 23:00
In my case there is no subrepos in my repo. I guess this problem is not linked to subrepos.

**Comment by kaeptmblaubaer1000** [comment] 2018-06-24 04:39
Since my recent `ExceptionDialog` addition, it's possible to get the Java stacktrace of this.
It is:
```
org.eclipse.jgit.api.errors.WrongRepositoryStateException: Wrong Repository State: SAFE

at org.eclipse.jgit.api.RebaseCommand.checkParameters(RebaseCommand.java:1268)

at org.eclipse.jgit.api.RebaseCommand.call(RebaseCommand.java:265)

at me.sheimi.sgit.repo.tasks.repo.ResetCommitTask.reset(ResetCommitTask.java:39)

at me.sheimi.sgit.repo.tasks.repo.ResetCommitTask.doInBackground(ResetCommitTask.java:23)

at me.sheimi.sgit.repo.tasks.repo.ResetCommitTask.doInBackground(ResetCommitTask.java:11)

at android.os.AsyncTask$2.call(AsyncTask.java:287)

at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)

at java.util.concurrent.FutureTask.run(FutureTask.java:137)

at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)

at java.lang.Thread.run(Thread.java:856)
```

**Comment by kaeptmblaubaer1000** [comment] 2018-06-24 04:41
This happens since MGit 1.5.3, the issue wasn't in MGit 1.5.2. I've no idea why it suddenly appeared, maybe a JGit upgrade?

**Closed** 2018-07-08 11:57 UTC
Labels: Priority, bug, investigating
