### ISSUE TITLE
MGit clone error: creating directories on sdcard failed

### ISSUE THREAD

**Issue by Monte-Christo** [maks/MGit#101] opened 2017-01-02 18:56 UTC
When trying to clone a repo with a root path on the external sdcard, MGit fials with the error message:

- Creating directories on [path to git root on sdcard] failed.

An identical clone operation with an internal memory location set to the git root path succeeds.

Internal memory is too precious to use for repo storage.

Android 5.1.1, Samsung Tab SM-T533

**Comment by VivianePons** [comment] 2017-01-17 14:25
Same here... I can select the sddrive but cannot clone a repo there

Android 5.0.1, Samsung Galaxy S4 GT-I9505

**Comment by maks** [comment] 2017-01-18 01:08
Apologies for not looking into this issue earlier and to @VivianePons for not having followed up on your previous issue about this.
I believe I found the issue thats is causing this now, [it's due to the a new permission required to access "secondary storage" android.permission.WRITE_MEDIA_STORAGE and in Android 5.0 onwards the enforcement of this permission being system privileged](http://stackoverflow.com/q/26744842/85472)

The solution will require implementing a completely different method to allow the user to choose the root location for MGit to use to store repos, but the current method/UI was only intended to be a stop gap measure anyway, so I've scheduled this as a high priority item for the next release.

**Comment by Bluscream** [comment] 2017-03-29 10:42
I have the same issue on my Galaxy Tab 9.3

**Comment by maks** [comment] 2017-05-08 02:49
After reading through the above SO especially t[his answer](http://stackoverflow.com/a/26765884/85472) sadly, its not going to be possible to support using "external sdcards" or any other storage that needs to be accessed via the Storage Access Framework as the SAF relies on clients using the DocumentFile instead of File class to do file manipulation (dir create, etc) which is then incompatible with jgit, the unerlying library MGit uses to do Git operations.
I'd be happy to be proved wrong, but until someone can suggest a work around, I'm closing this issue.

**Closed by maks** 2017-05-08 02:49 UTC
Labels: bug, wontfix

**Comment by maks** [comment] 2017-12-08 03:32
For future reference the official documentation on why write access to secondary external storage except via SAF: https://source.android.com/devices/storage/traditional
and SAF in not possible to use with jgit atm as jgit does not provide a filesystem abstraction to allow this.
On the bright side, the availability of [adopted storage](https://source.android.com/devices/storage/adoptable) gives users with Android 6.0 and higher the possiblity of using a sdcard as part of their storage that is accessible by jgit and hence MGit.

**Comment by aanno** [comment] 2019-03-19 21:59
Well, I'm not an Android developer (only a Java programmer). But I have used the app 'Total Commander' which is able to use the Sdcard (I.e. for creating a new folder). As a surprise it only opens the system dialog _once_ for the the top level folder (i.e. the Sdcard self). For any _nested_ folder it seems to me that the permission is already ( and permanently) granted. Perhaps such a method could be used in MGit as well?!?

**Comment by maks** [comment] 2019-03-19 23:31
@aanno as a Java dev I think you should realise that the issue is not to do with permissions but APIs. The SAF does *not* provide access via normal Java file i/o apis, you can just open a fileinput/outputstream for a string path using the SAF and that is what jgit expects as it does *not* have any filesystem abstractions.

Google docs are very clear about this:
>In Android 6.0, any device that is not adopted is considered portable. Because portable storage is connected for only a short time, the platform avoids heavy operations such as media scanning. Third-party apps must go through the Storage Access Framework to interact with files on portable storage; direct access is explicitly blocked for privacy and security reasons.

**Comment by kaeptmblaubaer1000** [comment] 2019-03-20 12:47
And using SAF would either need heavy modification of JGit or upgrading it (porting it using ASM)  and adding a new java.nio.file.FileSystem.

**Comment by kaeptmblaubaer1000** [comment] 2019-03-20 12:52
Unfortunately the latter isn't possible, because JGit uses java.io.File too much for that.

**Comment by maks** [comment] 2019-03-21 01:59
exactly. I'm (slowly) researching alternatives as being stuck with an ancient version of jgit has a number of downsides going forward.

**Comment by kaeptmblaubaer1000** [comment] 2019-03-21 14:58
I might try patching JGit to NNIO.2 using ASM if I get a bit more familiar
with it. javassist (like Retropiler uses) isn't usable very good, and I
haven't found a way to use dexlib2 (for this task it'd be way the easiest
solution if I had found a way). If I find some time, I'll try it again but
using ASM.

Maksim Lin <notifications@github.com> schrieb am Do., 21. März 2019, 02:59:

> exactly. I'm (slowly) researching alternatives as being stuck with an
> ancient version of jgit has a number of downsides going forward.
>

**Comment by crutchcorn** [comment] 2020-09-10 17:33
Has there been any news on migrating away from JGit for SAF usage? I'm building an app that requires Git usage, and am currently using JGit. @kb-1000 has there been any news on patching JGit? Maybe that's something you can I can do to work on together?

**Comment by maks** [comment] 2020-09-11 02:19
@crutchcorn Unfortunately I've been busy with other projects. My impression is that at the moment, it's not feasible to use compatibility shims to get a JGit that will work on Android version <10. so you'll need to instead create and maintain a patched fork of JGit that's usable on Android version <10. If you end up doing that please do let me know and I'll be happy to move over to it for MGit.

**Comment by crutchcorn** [comment] 2020-09-11 03:36
I legit may end up porting JGit bit-by-bit. I have specific needs that I'll be focusing on first, but I'll ping here with updates

**Comment by kb-1000** [comment] 2020-09-11 07:22
@crutchcorn I'm not patching JGit itself, I'm writing a partial java.nio.file replacement (good enough for JGit) and then patch its bytecode to use it.
It's not done yet.

**Comment by crutchcorn** [comment] 2021-04-26 22:31
@kb-1000 is this something you can help guide me on? I'd be willing to pay you for your time to make this a reality [or even just helping guide me on what you've done thus far] (and open-sourcing/contributing back to MGit as well)

An email you can reach me at (for more info) is visible in the patchfile from a recent commit I made:

`https://github.com/oceanbit/GitShark/commit/869095ba0e94e87bd99f0c1cf5f48295bdf80ba0 .patch`

**Comment by maks** [comment] 2021-04-26 23:31
@crutchcorn At this point I'd say you are better off not basing your app on JGIt. Especially given that you are looking to make GitShark cross platform, you would be better off looking at something like libgit2, though I think you would still need to do a fair bit of work to get it working with SAF, but at least it's feasible since AFAIK libgit2 allows for things like in custom filesystem implementations and I believe the wasm port of libgit2 does this to have a in-memory filesystm for example.

**Comment by crutchcorn** [comment] 2021-04-27 05:24
@maks a bit late on my end 😅 We're going open beta for Android this week and things are really stable with our testing. However, I still think JGit is the way to go (even if we have to fork/hotpatch) - here's why:

We actually looked into `libgit2` in the past, and I personally had a difficult time getting it compiled to Android. Further, even if we did get `libgit2` on Android we'd need bindings to Java (which [seem immature](https://github.com/ethomson/jagged) compared to [other lang bindings](https://github.com/libgit2/objective-git)), as we can't contain the FS in React Native (when we tried to do this, we hit OOM errors on nearly every op in larger repos [packfile] because the RN bridge doesn't allow streaming buffers, so you had to serialize all of your stuff into a B64 string in Java, then back to Buffer in JS).

Because of this, we're going to have to write a custom Git interop layer for each platform (iOS, Android, Desktop). We're already starting to use `libgit2` w/ [`objective-git`](https://github.com/libgit2/objective-git) bindings to write the Native code for iOS.

Further, our experience with JGit vs `libgit2` has been that JGit provides some REALLY nice ease-of-use functionality ([status](https://libgit2.org/libgit2/ex/HEAD/status.html), [log](https://libgit2.org/libgit2/ex/HEAD/log.html), etc) that are not provided OOTB and need to be ported to native code w/ `libgit2`. This is causing some headache for our iOS port as it seems like it's more difficult to write those ourselves and handle the edge-cases we're looking for as opposed to JGit which worked OOTB for 99% of what we needed.

**Comment by maks** [comment] 2021-04-28 00:41
@crutchcorn ah fair enough, and yes sorry about the slow response time, it seems you are very far along now.
And yes, choosing libgit2 does have its own compromises, I just expected that since you would already be using it for iOS it may make sense for Android as well, but yes if you are using React Native then there are other considerations as well.

I'd agree, JGit does have a very nice API with both high level and "porcelain" level APIs, which is one of the reasons I've used it from the beginning,

In regards to using JGit, it looks like you are using version 5 so I guess you are only targeting fairly new Android devices so for SAF support, you'd probably need to look at using an approach along the lines of [JGits in-memory filesystem](https://github.com/centic9/jgit-cookbook/blob/master/src/main/java/org/dstadler/jgit/porcelain/CloneRemoteRepositoryIntoMemoryAndReadFile.java) though depending on how you do it you may need to watch out for [these kinds of small gtochas](https://passingcuriosity.com/2020/jgit-in-memory-local-file-system/).

**Comment by crutchcorn** [comment] 2021-04-28 01:14
@maks no worries in the slightest re: response times. I honestly really appreciate you even responding now. Thank you so much for helping guide on SAF support - I'll be sure to take a look in the next few weeks to see what I can uncover

**Comment by crutchcorn** [comment] 2021-12-17 17:28
@kb-1000 I was wondering if you'd be comfortable doing a handoff of the `java.nio.file` bytecode patching code you'd mentioned starting work on?

I would love some pointers on where to start, and if you've already started some level of work (literally anything) that'd be the most helpful for me.

I'd be happy to both:

1) Financially compensate you for the handoff
2) Make sure it's OSS and contribute back to MGit once completed

If you'd want to chat more over email to avoid GH issue spam, the email listed in the header at this patch file works well:

`https://github.com/oceanbit/GitShark/commit/adaf2c9b788c72616be0ba0a1ef5e999759e37c7 .patch`

**Comment by JoshD522** [comment] 2024-03-02 18:53
@maks can you confirm that MGit still cannot use the SD card?  I did not see any mention of this limitation in the readme.  After quite a bit of searching, I came across this issue.
