### ISSUE TITLE
Editor of .ts files

### ISSUE THREAD

**Issue by VISHNUMURTHY** [maks/MGit#452] opened 2019-04-22 17:16 UTC
I am trying to open angular code files. This app is not supporting to edit .ts files. If you add editor for this one to it will be great help for users.

**Comment by kb-1000** [comment] 2019-04-23 06:10
We don't need to add an editor for them. Have you ever tried to open an angular file on a PC without any developer software installed? It by default opens a video player. It's more of a file association issue, which MGit hasn't caused.

**Comment by VISHNUMURTHY** [comment] 2019-04-23 13:40
Hi,

I hope you are misunderstood my feedback. Let me clarify you clearly.

Basically in PC if you are opening any kind of document. PC itself search
for the required application to open document and if application is not
available then it will ask user to choose any one application from
installed apps to open. If you have visual studio application in your
system then normally .ts files will open in it without asking user to
select application to open that file.

But, I gave feedback for the mobile app which is similar to PC in
functioning but not PC. What I observed in the app is HTML, CSS & JS files
are open normally in the embedded editor you have already provided in the
MGit app, but it is not opening TS(Type script) files which will be
normally used in angular application development.

Please find attachment for issue I am getting while trying to edit .ts
files.

What exactly I am advising is you can also pop-up an message for user to
select the editing apps or propose the user to install particular app which
can help user to open Type script files in mobile.

Regards,
Vishnu Murthy

**Comment by kb-1000** [comment] 2019-04-23 13:44
We neither need to add an editor nor a popup to install one. MGit already has a built-in one. The only thing that needs to be fixed is to map `.ts` to a `text/*` MIME type instead of a `video/*` MIME type, because the Android system recognizes `.ts` as a video file by default and MGit uses that functionality. All we need to do is add an option to enable this mapping.

**Comment by VISHNUMURTHY** [comment] 2019-04-23 14:02
Thanks in Advance. For whatever the implementation you will going to do to
open .ts files in MGit only.

I am waiting for your next app update where I can edit my .ts files also.

All the best & appreciate your development of MGIT app which will going to
help all the git repository users in future to edit files from their
mobiles only even in the absence of their Desktop/Laptop.

Regards,
Vishnu Murthy

**Comment by maks** [comment] 2019-07-10 10:24
yes the mime type simply needs to ammended

**Comment by maks** [comment] 2020-02-25 05:57
duplicate of #91

**Closed by maks** 2020-02-25 05:57 UTC
Labels: bug
