### ISSUE TITLE
Android 11 Storage Access

### ISSUE THREAD

**Issue by daimoniuma** [maks/MGit#639] opened 2022-05-19 23:25 UTC
Stopped work after system update to Android 11.

```
05-20 02:10:04.162 E/MediaProvider(3619): java.lang.IllegalArgumentException: Primary directory Github not allowed for content://media/external_primary/file; allowed directories are [Download, Documents]
05-20 02:10:04.162 E/MediaProvider(3619): 	at com.android.providers.media.MediaProvider.ensureFileColumns(MediaProvider.java:2923)
05-20 02:10:04.162 E/MediaProvider(3619): 	at com.android.providers.media.MediaProvider.ensureUniqueFileColumns(MediaProvider.java:2588)
05-20 02:10:04.162 E/MediaProvider(3619): 	at com.android.providers.media.MediaProvider.insertFile(MediaProvider.java:3282)
05-20 02:10:04.162 E/MediaProvider(3619): 	at com.android.providers.media.MediaProvider.insertInternal(MediaProvider.java:3827)
05-20 02:10:04.162 E/MediaProvider(3619): 	at com.android.providers.media.MediaProvider.insert(MediaProvider.java:3538)
05-20 02:10:04.162 E/MediaProvider(3619): 	at com.android.providers.media.MediaProvider.insertFileForFuse(MediaProvider.java:7200)
05-20 02:10:04.162 E/MediaProvider(3619): 	at com.android.providers.media.MediaProvider.insertFileIfNecessaryForFuse(MediaProvider.java:7294)
```

Works in Download and Documents directories only as written in the stack trace.

**Comment by maks** [comment] 2022-05-19 23:37
sadly this is a duplicate of #620

**Closed by maks** 2022-05-19 23:37 UTC
Labels: duplicate
