### ISSUE TITLE
External files not visible just folders

### ISSUE THREAD

**Issue by s-aluma-r** [maks/MGit#642] opened 2022-05-29 17:44 UTC
**Describe the bug**
Used obsidian app to create a new vault with notes in the repository but when I open the repository in mit it only shows the folders created by obsidian and the previously cloned vaults with all files...

So basically MD files that have been cloned by mgit are visible just as files created by the file explorer but not those created by obsidian even after changing access rights to read write for user and everyone

**To Reproduce**
- Steps to reproduce the behavior:
- Create GitHub repo
- Create obsidian vault inside it
- Clone repro
- Open in obsidian mobile
- Create new note
- Try to commit and push with mgit
 (File not visible)

**Expected behavior**
The files should be visible and commitable

**Screenshots**
Not needed just an empty folder except .obsidian folder inside Wich is also empty

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 4a5g]
 - OS: [e.g. Android 12]
 - App Version [e.g. 1.6.2]

**Additional context**
//

**Comment by JoernSchoenyan** [comment] 2022-05-29 20:04
I'm seeing the exact same problem on a Xiaomi Mi Note.

**Comment by maks** [comment] 2022-05-30 01:12
Sadly also a duplicate of #620

**Closed by maks** 2022-05-30 01:12 UTC
