### ISSUE TITLE
MGit doesn't save Login Data (Personal Acces Tokens)

### ISSUE THREAD

**Issue by ItsJamin** [maks/MGit#625] opened 2022-04-11 15:33 UTC
**Describe the bug**
I looked around and didn't saw a topic on this issue. I am sorry if it is redundant:

So on MGit it doesn't save the login data (and yes I checked the box under the login screen to save). Is this a common problem with personal acces tokens? If so what other options can I use to login that will work (I am very new in the gitHub community)?

This leads to only being logged in until I close the App. If I start it no login data is saved.

**Expected behavior**
Login Data will be saved so that the login screen doesn't even come up or comes up filled out with the saved ifnormation.

**Smartphone (please complete the following information):**
 - Device: Galaxy A20e
 - OS: Android 11
 - App Version 1.6.2

**Additional context**

**Comment by maks** [comment] 2022-04-15 07:18
Thank you for reporting this. I don't think this is specific to access tokens as there was already an issue with saving passwords (which auth tokens are treated in the same way by MGit) so I think this is a duplicate of #246 which I really need to find some time to look into asap.

**Closed by maks** 2022-04-15 07:18 UTC
