### ISSUE TITLE
I am unable to give sd card writing/reading autorizations via the app.

### ISSUE THREAD

**Issue by Moota-0** [maks/MGit#634] opened 2022-05-02 21:10 UTC
A way of getting to the "Files" menu and select the SD card and click the authorize access to the SD card.

I could use internal storage or root my android phone but it is not in my plans and could be useful for other users in the same case as me.

I am unable to provide a screenshot of the implementation made from other apps that asked for this authorization, but I can provide it if needed.

@Moota-0

Edit : 
Here's google guide for the Files app : 
https://storage.googleapis.com/support-kms-prod/PtGGATI3Ouz99XpvgNEvM5GPezj8dDt8m7bu

From : [Google Files support page](https://support.google.com/files/answer/9321529?hl=en)

**Comment by maks** [comment] 2022-05-13 00:49
Duplicate of #553  and #620

**Closed by maks** 2022-05-13 00:49 UTC
Labels: duplicate
