### ISSUE TITLE
Inflater Error

### ISSUE THREAD

**Issue by hermanmakhm** [maks/MGit#590] opened 2021-11-29 23:03 UTC
**Describe the bug**
After a pull error with conflicts I decided to delete the original local repo and start over. When I try to download everything again from the private remote GitHub repo it downloads and then says "Inflater has been closed"

**To Reproduce**
1. Delete old repo
2. Remove SSH key (not necessary)
3. Recreate SSH key
4. Paste into GitHub key
5. Use GitHub address for .git for SSH
6. Wait
7. Error

**Expected behavior**

**Screenshots**
![Screenshot_20211129-235516.png](https://user-images.githubusercontent.com/26993173/143955957-829f1e7e-79c5-4a62-9aff-30d1a3bf44ab.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 12
 - App Version 1.5.10

**Additional context**
Attempted fix by clearing storage and deleting cache from app info and reinstalling app. Also repo has slightly large files.

**Comment by maks** [comment] 2021-12-02 21:23
Duplicate of #54

**Closed by maks** 2021-12-02 21:23 UTC
Labels: duplicate
