### ISSUE TITLE
Not able to clone outside of Android/data/ dir

### ISSUE THREAD

**Issue by HenriqueCarloFarina** [maks/MGit#648] opened 2022-07-23 17:17 UTC
Hi guys, I am trying to clone a repo in a common dir of my android 12 phone so I can open the files with an editor of my choice. Everytime I change the root dir for cloned repos the app fails cloning repos with "operation not permitted". It is a bit sad because the only place I can clone is if I don't change the default and the repo clone goes to: '/storage/emulated/0/Android/data/com.manichord.mgit/files/repo' but then no other app can open the files saved in this dir. Is this something I am doing wrong? Is there any configuration that I can change to make the clones work at something like 'storage/emulated/0/local_repos'?

**Comment by maks** [comment] 2022-07-24 00:49
Sadly this is a duplicate of #620. I'm working on a potential fix but its not yet ready.

**Closed by maks** 2022-07-24 00:49 UTC
Labels: duplicate
