### ISSUE TITLE
Unable to select a path in storage

### ISSUE THREAD

**Issue by waleslau** [maks/MGit#549] opened 2020-08-02 17:13 UTC
**Describe the bug**
Unable to select a path in storage.
I only see '/storage/emulated/0', but I don't see the files and subdirectories in that directory in the software

**To Reproduce**
When I want to import repo or want to set the root storage location of the repos

**Expected behavior**
As I described in **Describe the bug**

**Screenshots**

![Screenshot_2020-08-03-01-12-05-274_com.manichord.mgit.jpg](https://i.loli.net/2020/08/03/TiJPmtwZezA7sh8.jpg)
![Screenshot_2020-08-03-01-11-58-067_com.manichord.mgit.jpg](https://i.loli.net/2020/08/03/Uhy9TGmqbWunOLs.jpg)

**Smartphone:**
 - Device: Redmi Note7 Pro
 - OS: Android 10 (MIUI 12)
 - App Version 1.5.9

**Comment by waleslau** [comment] 2020-08-02 17:26
Add a picture.

![Screenshot_2020-08-03-01-12-05-274_com.manichord.mgit.jpg](https://i.loli.net/2020/08/03/TiJPmtwZezA7sh8.jpg)
![Screenshot_2020-08-03-01-11-58-067_com.manichord.mgit.jpg](https://i.loli.net/2020/08/03/Uhy9TGmqbWunOLs.jpg)

**Comment by maks** [comment] 2020-08-02 21:06
Duplicate of #542

**Closed** 2020-08-02 21:06 UTC
