### ISSUE TITLE
I can not give the MGit "All File Permission"

### ISSUE THREAD

**Issue by aldwen** [maks/MGit#671] opened 2023-01-04 13:37 UTC
**Describe the bug**
I had a Huawei phone, and MGit works OK in that phone.
Recently, I brought a new phone : redmi K50 pro.
MGit can not work on K50pro, I got the message of "Operation not permitted". I know the app needs "All File Permission". But I could not give that Permission to MGit. 
It seems that MGit not request the Permission in my phone. and I searched in the setting for give Permission to MGit, but I falled.
Do someone knows how to resolve it?

**Comment by maks** [comment] 2023-01-05 00:12
Unfortunately this is a duplicate of #620 and the only solution for now is to use the version of [MGit distributed from F-Droid](https://f-droid.org/packages/com.manichord.mgit/) on devices running Android 11+.

**Closed as completed by maks** 2023-01-05 00:12 UTC
Labels: duplicate
