### ISSUE TITLE
Clone Failure on MGit

### ISSUE THREAD

**Issue by clef-shanty** [maks/MGit#608] opened 2022-03-19 01:31 UTC
Using MGit for a while and now it will not pull, push, or clone.  I keep getting I keep getting a popup for Invalid remote.  If try to clone the directory, it says Invalid remote Clone failed.

**Comment by tommcc** [comment] 2022-03-22 19:25
@clef-shanty was your error when trying to clone a GitHub repo, by any chance? They just recently made a change that rejects new-ish RSA keys with less than 4096 bits, [recommending](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key) either generating either a new RSA with `-b 4096` or using ed25519 algorithm. I ran into this on another machine this week so it's fresh on my mind.

**Comment by clef-shanty** [comment] 2022-03-22 20:46
It actually started on a repository I had already been using. The key was generated in app using rsa at 4096. It is the same key I used before it broke. 

Now I've tried to regenerate a new key in the app using rsa 4096. Still can't re clone the repository. 

I tried regenerating a key in the terminal using ed25519 and then downloading the public key to Mgit, but Mgit makes it a private key and that doesn't work. 

Is there a way to get my public key downloaded into Mgit as a public key and not a private key?

**Comment by tommcc** [comment] 2022-03-22 20:53
Ah rats, that wasn't the issue then. I'm getting the same error and was grasping at straws.

The device doing the connecting will always need the private key, which I'm guessing MGit is obscuring (and only revealing the public key).

Not sure how we can find out a more specific error.

**Comment by maks** [comment] 2022-03-22 21:44
This is actually a duplicate of #601.

Please note that per the comments there, Github stopped allowing ssh keys with outdated and no longer secure algorithms.

Per the last few comments in #601, this has now been fixed by **either** importing a `ed25519` created else where **or** generating a new RSA key in MGit (with the default 4096 length) using the **LATEST BETA** version `1.6.2` of MGit that I just released on MGits Beta channel on Google Play about 10hours ago.  

I have just tested using MGit `1.6.2` generating a new RSA, adding it to a Github account and using it to cloen a repo successfully over ssh.

**Closed by maks** 2022-03-22 21:44 UTC
