### ISSUE TITLE
Operation not permitted error

### ISSUE THREAD

**Issue by UnrealKaraulov** [maks/MGit#662] opened 2022-12-06 00:43 UTC
Where is GitHub login to commits/push back repository changes? I can't import repository from GitHub and cant push any changes??

**Comment by maks** [comment] 2022-12-06 01:56
You will need to create a personal auth token on Github and use that as your password when authenticating via HTTPS with your github user email. Please see [here](https://github.com/maks/MGit/issues/618#issuecomment-1093822067) and [here](https://github.com/maks/MGit/issues/584#issuecomment-936918967).

**Comment by UnrealKaraulov** [comment] 2022-12-06 05:48
@maks 
But I got this error after pressing '+' button.

**Comment by UnrealKaraulov** [comment] 2022-12-06 07:42
@maks in "Spck Code Editor / Git Client" https://play.google.com/store/apps/details?id=io.spck
I just enter github generated token. 
And it can clone any repository, and I can edit any file and then do pull/push changes)

In MGit i can't see option 'GitHub token' or something like it, just got error when press '+' button.

**Comment by UnrealKaraulov** [comment] 2022-12-07 04:54
I not have local repositories. After press '+' button, I see 'Operation not permitted" error and no more other windows.

**Comment by maks** [comment] 2022-12-07 05:04
You don't need to have any existing local repositories to clone a remote repository. 
I'm sorry I don't know why you would be seeing that error. 
It would help if could you please take a screenshot of the error dialog you are seeing and attach it here.

**Comment by a-blekot** [comment] 2022-12-12 20:55
I have created ssh key using MGit and then added it to GitHub. And now I can clone repo using ssh 🙂

**Comment by katio** [comment] 2022-12-13 02:50
I tried also with ssh key Yesterday and today again, to no avail. The same error

**Comment by Hanni87** [comment] 2022-12-21 15:50
I have the same error as above with the failed operation. Tried it via SSH, https and with different settings. Phone is Pixel 6 with Android 13.

**Comment by lucastucious** [comment] 2022-12-22 17:41
Same error... Created a ssh key with mgit, added to gitea and trying to clone

**Comment by JonSmith2017** [comment] 2022-12-23 06:06
I meet the same error

**Comment by lucastucious** [comment] 2022-12-23 08:16
> I meet the same error

Try to change the default repo location

**Comment by katio** [comment] 2022-12-23 15:11
@lucastucious Can you please explain what you mean? In Mgit? In Github? Where is that? Is your repo prívate?

**Comment by lucastucious** [comment] 2022-12-23 16:08
In mgit ![Screenshot_2022-12-23-17-07-45-60_07c4ca94ee412a5e51d7ba7f5fce4152.jpg](https://user-images.githubusercontent.com/28046122/209365159-42a8c69f-9e56-4677-a336-33ab56c3168f.jpg)

**Comment by katio** [comment] 2022-12-23 17:26
@lucastucious thx. It works on the download folder!
Any way to add permissions to a different folder with a better name?

**Comment by Hanni87** [comment] 2022-12-23 17:49
I can confirm with download it works. With other folders it doesn't.

**Comment by katio** [comment] 2022-12-24 20:24
It also works on the Documents folder. It seems related to new Android restrictions in new Android versions https://stackoverflow.com/questions/73845858/failed-to-save-files-on-storage-filesystemexception-flutter

**Comment by maks** [comment] 2023-01-01 04:41
Unfortunately this is also a duplicate of #620 due to restrictions on use of the "all files" permission. Please see the latest comment by me on that issue for the current state of play [sic].

**Closed by maks** 2023-01-01 04:41 UTC
Labels: question

**Comment by iqijun** [comment] 2026-02-28 06:04
Two possible reasons 
1. Repository Contains Special Characters Unsupported by the Android File System (Most Common) ， Prohibited Characters: \, :, *, ?, ", <, >, |
2. Repository Contains "Symbolic Links (Symlinks)"
