### ISSUE TITLE
type script support

### ISSUE THREAD

**Issue by abadakhshan** [maks/MGit#100] opened 2016-12-30 15:26 UTC
Hi
Pls add support of type script file in app
Currently i cant view ts files content in app.

**Comment by maks** [comment] 2017-01-02 03:49
This needs to be done in the CodeMirror-based editor that is shipped within MGit.
PRs are welcome if you would liek to have a go at this, the relevant files are in:
https://github.com/maks/MGit/tree/master/src/main/assets

**Comment by justdave** [comment] 2017-01-02 09:30
duplicate of #91?

**Comment by abadakhshan** [comment] 2017-01-02 10:15
Yes
duplicate of #91
When click on ts file external app opened

**Comment by kaeptmblaubaer1000** [comment] 2018-06-07 15:29
@maks is it a standard CodeMirror, or a modded one?

**Comment by maks** [comment] 2018-06-07 22:12
It's a stock CM just very old. My plan is to update it and make some fixes but break it out into it's own module and preferably separate app. I think I already have issues here for that work.

**Comment by maks** [comment] 2020-02-25 04:17
Internal editor is going to be removed: #504

**Closed by maks** 2020-02-25 04:17 UTC
Labels: editor, enhancement
