### ISSUE TITLE
Reset (HARD) produce an error every time

### ISSUE THREAD

**Issue by Zykino** [maks/MGit#195] opened 2017-08-05 14:56 UTC
I downloaded github.com/mxqmn/WaveFunctionCollapse at 3bd36bf5fd01f4e3494cc82076aea959540b68a8

Opened the Readme and closed it without modification.
A space must have been changed anyway and when I want to reset I get:

org.eclipse.jgit.api.RebaseCommand.checkParameters(RebaseCommand.java:1268)
org.eclipse.jgit.api.RebaseCommand.call(RebaseCommand.java:265)
me.sheimi.sgit.repo.tasks.repo.ResetCommitTask.reset(ResetCommitTask.java:39)
me.sheimi.sgit.repo.tasks.repo.ResetCommitTask.doInBackground(ResetCommitTask.java:23)
me.sheimi.sgit.repo.tasks.repo.ResetCommitTask.doInBackground(ResetCommitTask.java:11)
android.os.AsyncTask$2.call(AsyncTask.java:305)
java.util.concurrent.FutureTask.run(FutureTask.java:237)
android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
java.lang.Thread.run(Thread.java:761)

I didn't intended to make a change and wanted to keep a clean repo.

MGit 1.5.2
OnePlus 3 Android 7.1.1

**Comment by kaeptmblaubaer1000** [comment] 2018-06-23 18:07
Duplicate of #238.

**Closed** 2018-07-08 11:57 UTC
Labels: bug, investigating
