### ISSUE TITLE
Cannot open git-receive-pack

### ISSUE THREAD

**Issue by ShalokShalom** [maks/MGit#249] opened 2018-01-19 07:28 UTC
I get this error when I like to upload something onto 

Https://try.gitea.io/ShalokShalom/start

**Comment by maks** [comment] 2018-01-31 10:00
I suspect this is a compatibility issue with the git implementation used by gitea.

**Comment by maks** [comment] 2018-01-31 10:05
duplicate of #248

**Closed by maks** 2018-01-31 10:05 UTC

**Comment by ShalokShalom** [comment] 2018-02-10 08:56
Seems to be otherwise: https://github.com/go-gitea/git/issues/109#issuecomment-364630964
