### ISSUE TITLE
Android 11 "Error occurred" message when open external local repo

### ISSUE THREAD

**Issue by rooneyc** [maks/MGit#613] opened 2022-03-27 15:59 UTC
**Describe the bug**
"Error occurred" message when open external local repo

**To Reproduce**
- Uninstll MGit 1.6.2
- Install MGit 1.6.2
- Open MGit
- When prompted, Allow MGit access to photos and media on device
- An old external local repo is displayed
- Tapping on old repo leads to the "Error occurred" message
- Press ok to the "Error occurred" message
- Delete old external local repo
- Confrm Delete
- Rap Import Repository
- Choose folder
- Tap save icon
- Confirm import
- Check "Import as external repo"
- Tap Import
- Repo imported
- Tap on repo "Error occurred" message
- Tap on menu
- Tap Raw Config, get "Error occurred Can't open file in this device" message

**Expected behavior**
Newly imported external local repo should open and no error message should be displayed

**Screenshots**
![Screenshot_20220327-162414](https://user-images.githubusercontent.com/7915677/160289927-4202128b-456f-496c-8d98-8f670aaeae6d.png)

**Smartphone (please complete the following information):**
 - Device: moto g(30)
 - OS: Android 11 Build RRCS31.Q1-3-68-4
 - App Version 1.6.2

**Additional context**
I have carried out the steps above a number of times and can recreate each time.
If there is anything else I can provide or do please let me know.
I would be happy to provide a stack trace but would need a little guidance on how to do so

**Comment by leoweyr** [comment] 2022-03-28 05:27
## I HAVE A SIMILAR ERROR
1. Setting > General > Root storage location for repos as picture:
![20220328132616](https://user-images.githubusercontent.com/58080150/160331994-fd0815e9-3a0c-4544-a777-8070174c6f1e.jpg)

2.Clone repo from Github corrently, and then:
![20220328132609](https://user-images.githubusercontent.com/58080150/160332005-3436860c-0466-4a56-a1bc-d46815059b8d.jpg)

**Comment by sdenaro** [comment] 2022-04-01 18:02
Same issue with Android 12 on Pixel 5.

**Comment by maks** [comment] 2022-04-02 22:28
Sorry everyone about this issue. This is due to the latest version of MGit having to target latest Android SDK version (per Google Play policies) and so on newer Android versions: 11 and above, this means MGit no longer has access to most "external" (ie. `/storage/emulated/0/`).
 
This is actually a duplicate of #615.

Per comments in #615, this can be worked around by either copying  an existing local repo (using a file manager app) or re-cloning to a "allowed known" location like `/storage/emulated/0/Documents`.

A fix for this in MGit itself is being tracked in #465.

**Closed by maks** 2022-04-02 22:28 UTC
Labels: bug, investigating
