### ISSUE TITLE
android.content.res.Resources$NotFoundException: File res/drawable/ic_default_author.xml

### ISSUE THREAD

**Issue by garbarick** [maks/MGit#360] opened 2018-05-26 17:19 UTC
android.content.res.Resources$NotFoundException: File res/drawable/ic_default_author.xml from drawable resource ID #0x7f020072. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
at android.content.res.Resources.loadDrawable(Resources.java:2097)
at android.content.res.Resources.getDrawable(Resources.java:700)
at com.nostra13.universalimageloader.core.DisplayImageOptions.getImageOnFail(DisplayImageOptions.java:142)
at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask$2.run(LoadAndDisplayImageTask.java:358)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5017)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
at dalvik.system.NativeStart.main(Native Method)
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
at android.content.res.Resources.loadDrawable(Resources.java:2093)
... 12 more
org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
at android.content.res.Resources.loadDrawable(Resources.java:2093)
at android.content.res.Resources.getDrawable(Resources.java:700)
at com.nostra13.universalimageloader.core.DisplayImageOptions.getImageOnFail(DisplayImageOptions.java:142)
at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask$2.run(LoadAndDisplayImageTask.java:358)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5017)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
at dalvik.system.NativeStart.main(Native Method)

**Comment by kaeptmblaubaer1000** [comment] 2018-05-26 18:20
Duplicate of #300

**Comment by kaeptmblaubaer1000** [comment] 2018-05-26 18:20
@maks seems like more and more users hit this.

**Comment by maks** [comment] 2018-06-03 05:43
Please see #300

**Closed by maks** 2018-06-03 05:43 UTC
Labels: bug, duplicate

**Comment by maks** [comment] 2018-06-03 05:48
The release with a fix (1.5.4.4)  is now available in the Play Beta channel: https://play.google.com/apps/testing/com.manichord.mgit
