### ISSUE TITLE
Inflater has been closed

### ISSUE THREAD

**Issue by imshenwei** [maks/MGit#605] opened 2022-02-13 09:16 UTC
**Describe the bug**
keep popping up "Inflater has been closed"

**To Reproduce**
Don't know how to 
Yet no happend before, It has been used normally for several months
It hasn't worked for days now

**Screenshots**
![image](https://user-images.githubusercontent.com/64460759/153746469-0ccfcab6-d6dd-4935-a339-bfcaf0a379be.png)

**Smartphone (please complete the following information):**
 - Device: Redmi K30 Pro Edition
 - OS: MIUI 12.5.7
 - App Version 1.5.10

**Comment by maks** [comment] 2022-02-14 03:03
Thank you for opening this issue, but it seems to be a duplicate of #54

**Closed** 2022-02-14 03:03 UTC
Labels: duplicate
