### ISSUE TITLE
Can't Clone

### ISSUE THREAD

**Issue by timmy61109** [maks/MGit#426] opened 2018-10-07 06:31 UTC

**Comment by RB-Lab** [comment] 2019-03-07 11:28
Duplicate of #428

**Comment by kaeptmblaubaer1000** [comment] 2019-03-07 14:23
No. This issue does not have enough information to be considered duplicate. It might be invalid, but definitely not duplicate, how do you know what was tried to do and what happened instead? And how do you know that this is exactly the same as in #428? Just based on the name? Nope.

**Comment by timmy61109** [comment] 2019-03-08 03:30
其實有一點不一樣，他使用SSH，但我們的共通點是更改放置儲存庫的路徑。
In fact, there is a difference, he uses SSH, but our common point is to change the path to place the repository.

**Comment by kaeptmblaubaer1000** [comment] 2019-03-08 10:36
See? This makes this issue completely different. That issue was caused by
an exception in JSCH, the SSH library JGit and in turn MGit uses, and
changing the directory **has *nothing* to do with that**, unless you can
prove the opposite, maybe by posting more information? But, as I said NO
DUPLICATE

Wu Chenzhi <notifications@github.com> schrieb am Fr., 8. März 2019, 04:30:

**Comment by timmy61109** [comment] 2019-03-09 14:59
儲存位置更改不是也會影響到？
Will storage location changes also affect?

**Comment by kaeptmblaubaer1000** [comment] 2019-03-09 15:01
How should I know this without more information like the error report? I don't have access to those emails, it would be nice if you copied its contents here

**Comment by timmy61109** [comment] 2019-03-10 07:53
USER_COMMENT=
ANDROID_VERSION=8.0.0
APP_VERSION_NAME=1.5.4.7
BRAND=asus
PHONE_MODEL=ASUS_Z01KD
CUSTOM_DATA=
STACK_TRACE=java.lang.IllegalStateException: Inflater has been closed
at java.util.zip.Inflater.ensureOpen(Inflater.java:400)
at java.util.zip.Inflater.reset(Inflater.java:354)
at org.eclipse.jgit.lib.InflaterCache.release(InflaterCache.java:92)
at org.eclipse.jgit.internal.storage.file.WindowCursor.release(WindowCursor.java:371)
at org.eclipse.jgit.internal.storage.file.PackInputStream.close(PackInputStream.java:83)
at java.util.zip.InflaterInputStream.close(InflaterInputStream.java:239)
at java.io.BufferedInputStream.close(BufferedInputStream.java:485)
at org.eclipse.jgit.lib.ObjectStream$Filter.close(ObjectStream.java:229)
at org.eclipse.jgit.lib.ObjectLoader.copyTo(ObjectLoader.java:268)
at org.eclipse.jgit.dircache.DirCacheCheckout.checkoutEntry(DirCacheCheckout.java:1244)
at org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:451)
at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:396)
at org.eclipse.jgit.api.CloneCommand.checkout(CloneCommand.java:251)
at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:135)
at me.sheimi.sgit.repo.tasks.repo.CloneTask.cloneRepo(CloneTask.java:71)
at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:38)
at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:23)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)

**Comment by timmy61109** [comment] 2019-03-10 07:54
我只有這些了。
I only have these.

**Comment by timmy61109** [comment] 2019-11-29 08:37
I know why there is no way to clone, because I set the path on the SD card, but because the program does not support saving to external space, an error occurs, I hope this can be resolved.

**Closed** 2019-12-02 01:55 UTC
