### ISSUE TITLE
Do not show up-folder in Settings->SSH Keys

### ISSUE THREAD

**Issue by maks** [maks/MGit#326] opened 2018-04-19 01:47 UTC
Currently the user is able to navigate out of the private data storage folder that MGit uses to store ssh keys using ".." entry - this should not be possible as its just confusing to users.

**Comment by mkroehnert** [comment] 2018-06-10 22:20
Hi, I am not sure, if the issue described below should be part of this ticket. Please let me know, if I should create a separate ticket instead.

This is based on the latest MGit (1.5.4.4) from the Playstore beta channel on an Android 8.0.0 device with German locale. I have manually enabled access to the filesystem (see #345), so this should not be an issue.

After generating a new SSH key pair with `... -> Settings -> SSH Keys -> ... -> Generate Key`. I selected a `rsa-key` as filename, left the default values for RSA 4096, and pressed `Generate Key` in the dialog.
Next, the file `data/user/0/com.manichord.mgit/files/ssh/rsa-key` is shown and pressing on it shows the content of the private key.

Then, I wanted to access the public key, which I need in order to grant me access to Git services like GitHub or GitLab.
Thus I select `..` above the `rsa-key` file, which shows me the two directories `ssh` and `sshpub`.
However, I can not access the public key, since I get `Error occurred. Error: The file can not be opened on this device` if I click on any of the two listed directories.

**Comment by maks** [comment] 2018-06-11 11:08
@mkroehnert  Thanks for reporting this, yes I can replicate the issue you are having. 
Its not the same problem that this issue covers so do please open a new issue. I'm a bit busy at the moment with other things but I'll try to get this fixed as soon as I can.

**Comment by kaeptmblaubaer1000** [comment] 2018-06-11 11:40
@maks it's just the problem that occurs because of this UX issue.
If this is fixed, then the problem isn't possible anymore.
@mkroehnert it would be a duplicate (I'm currently unable to find it because of a *very* slow browser).

**Comment by mkroehnert** [comment] 2018-06-12 11:59
I won't open a new ticket then, according to the comment from @kaeptmblaubaer1000 .

Thank you for your work on this application and the quick replies.

**Comment by kaeptmblaubaer1000** [comment] 2018-06-14 16:11
@mkroehnert okay, I wrongly understood your comment.
The `ssh-rsa` line (that was probably shown what you called "private key") is the public key, to access the private key:
<img src="https://user-images.githubusercontent.com/18211838/41424267-d398fe06-6ffd-11e8-85e3-9cea5f9b5bf4.png" width="216" height="384" />
you have to select the key by long-press, access the menu in the upper-right corner and tap "Show private key".

**Comment by mkroehnert** [comment] 2018-06-14 20:18
@kaeptmblaubaer1000 thanks for the update and clarification. I can confirm that this works on my device, too. And sorry for hijacking this ticket.

In my opinion, this is a point which should be addressed by the SSH UI/UX ticket, since this behavior was not obvious to me.

**Comment by maks** [comment] 2018-06-14 22:14
Yes big thanks to @kaeptmblaubaer1000. I didn't have time to look at the code and had forgotten myself that's where the functionality is! as I don't use SSH with MGit much myself.
I agree this is dreadful UX as it's completely not obvious or easily discoverable. I'll open a new ticket for that.

**Closed** 2018-06-14 22:14 UTC
Labels: bug, ui/ux
