### ISSUE TITLE
Cannot find .pub file

### ISSUE THREAD

**Issue by thenewkgb** [maks/MGit#651] opened 2022-09-01 20:07 UTC
**Describe the bug**
After creating a key on my PC I upload my public key to my phone but exploring files in MGit SSH file manager does not show file. Only folders.

**To Reproduce**
1. Create SSH key on PC
2. Upload .pub file to phone
3. Open MGit
4. In settings-> manage ssh key
5. Click down arrow (explore files)
6. Navigate to .pub file

**Expected behavior**
I would expect to navigate to a folder and see my .pub file in a file explorer.

**Screenshots**
![Screenshot_20220901-210452.png](https://user-images.githubusercontent.com/74326914/188002365-00b46688-a1d2-4598-8bbd-3351ed78ded9.png)

**Smartphone (please complete the following information):**
 - Device: Moto g50

**Additional context**
Sorry about smartphone description but now I cannot discard this bug report.

**Comment by maks** [comment] 2022-09-01 23:09
Could you please provide the Android version your phone is running?

**Comment by thenewkgb** [comment] 2022-09-02 00:23
Apologies. I'm running Android 12.

**Comment by maks** [comment] 2022-09-02 00:48
@thenewkgb unfortunately that means this is a duplicate of #620

**Closed by maks** 2022-09-02 00:48 UTC
Labels: more info required
